import { apiFetch } from "../config/api";
import {useEffect,useState} from 'react';import {API_URL} from '../config';import '../auth/account.css';
export default function AccountPage({onBack}){const [user,setUser]=useState(null),[profile,setProfile]=useState(null),[form,setForm]=useState({}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
const load=async()=>{const [u,p]=await Promise.all([apiFetch(`${API_URL}/api/account/me`).then(r=>r.json()),apiFetch(`${API_URL}/api/profile`).then(r=>r.json())]);setUser(u.user);setProfile(p.profile);setForm({...p.profile,goals:{...(p.profile.goals||{})}})};useEffect(()=>{load()},[]);
const set=(k,v)=>setForm(x=>({...x,[k]:v}));const setGoal=(k,v)=>setForm(x=>({...x,goals:{...x.goals,[k]:v}}));
async function save(e){e.preventDefault();setBusy(true);setMsg('');try{const r=await apiFetch(`${API_URL}/api/profile`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.message||'Save failed');setProfile(d.profile);setMsg('Profile saved ✓')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
function logout(){localStorage.removeItem('mydailyos_token');localStorage.removeItem('mydailyos_user');window.location.reload()}
async function del(){if(!confirm('Delete your entire MyDailyOS account and all personal data? This cannot be undone.'))return;setBusy(true);const r=await apiFetch(`${API_URL}/api/account/me`,{method:'DELETE'});const d=await r.json();if(!r.ok)return setMsg(d.message||'Delete failed');localStorage.clear();window.location.reload()}
return <div className="page-card"><div className="section-header"><div><h2>Account & Profile</h2><p>One account keeps your web and mobile data in sync.</p></div><button className="secondary-button" onClick={onBack}>← Dashboard</button></div><div className="account-box"><strong>{user?.name}</strong><span>{user?.email}</span><button className="secondary-button" onClick={logout}>Logout</button></div><form className="profile-form" onSubmit={save}><h3>Personal profile</h3><label>Name<input value={form.name||''} onChange={e=>set('name',e.target.value)}/></label><label>Age<input type="number" value={form.age??''} onChange={e=>set('age',e.target.value?Number(e.target.value):null)}/></label><label>Height (cm)<input type="number" value={form.heightCm??''} onChange={e=>set('heightCm',e.target.value?Number(e.target.value):null)}/></label><label>Current weight (kg)<input type="number" step="0.1" value={form.currentWeightKg??''} onChange={e=>set('currentWeightKg',e.target.value?Number(e.target.value):null)}/></label><h3>Goals</h3><label>Calories<input type="number" value={form.goals?.calorieTarget||''} onChange={e=>setGoal('calorieTarget',Number(e.target.value))}/></label><label>Protein (g)<input type="number" value={form.goals?.proteinTarget||''} onChange={e=>setGoal('proteinTarget',Number(e.target.value))}/></label><label>Water (ml)<input type="number" value={form.goals?.waterTargetMl||''} onChange={e=>setGoal('waterTargetMl',Number(e.target.value))}/></label><label>Target weight (kg)<input type="number" step="0.1" value={form.goals?.targetWeightKg??''} onChange={e=>setGoal('targetWeightKg',e.target.value?Number(e.target.value):null)}/></label>{msg&&<p>{msg}</p>}<button className="primary-button" disabled={busy}>{busy?'Saving…':'Save profile'}</button></form><div className="danger-box"><h3>Danger zone</h3><p>Delete this account and all personal logs permanently.</p><button className="danger-button" onClick={del}>Delete account</button></div></div>}
