// Plain-text layout of the dietitian report (rendered to PDF by lib/pdfReport.js). Pure: no database access.
const pad = (s, n) => String(s).slice(0, n).padEnd(n);
const lpad = (s, n) => String(s).slice(0, n).padStart(n);
const r0 = (x) => Math.round(Number(x) || 0);
const r1 = (x) => (Math.round((Number(x) || 0) * 10) / 10).toString();
const MEAL_ORDER = ['breakfast', 'lunch', 'dinner', 'snacks'];

function buildReportLines({ user, profile, targets, days, foodLogs, from, to, weight }) {
  const L = [];
  const h = (t) => L.push({ text: t, bold: true });
  h('FLEXFIT - NUTRITION & PROGRESS REPORT');
  L.push(`Name: ${user?.name || '-'}    Period: ${from} to ${to}`);
  L.push('');
  h('PROFILE & TARGETS');
  L.push(`Age ${profile?.age ?? '-'}, ${profile?.sex || '-'}, height ${profile?.heightCm ?? '-'} cm, weight ${profile?.currentWeightKg ?? '-'} kg, goal weight ${profile?.goals?.targetWeightKg ?? '-'} kg`);
  L.push(`Daily targets: ${r0(targets.calories)} kcal | protein ${targets.protein} g | carbs ${targets.carbs} g | fat ${targets.fat} g | fibre ${targets.fiber} g`);
  L.push('');

  const logged = days.filter((d) => d.calories > 0);
  const avg = (k) => (logged.length ? logged.reduce((s, d) => s + (Number(d[k]) || 0), 0) / logged.length : 0);
  h('AVERAGES (days with food logged)');
  L.push(`Days logged: ${logged.length} of ${days.length}`);
  L.push(`Energy ${r0(avg('calories'))} kcal | protein ${r1(avg('protein'))} g | carbs ${r1(avg('carbohydrates'))} g | fat ${r1(avg('fat'))} g | fibre ${r1(avg('fiber'))} g | sugar ${r1(avg('sugar'))} g`);
  L.push(`Water ${r0(days.reduce((s, d) => s + d.waterMl, 0) / Math.max(days.length, 1))} ml/day | exercise ${r0(days.reduce((s, d) => s + d.exerciseMinutes, 0) / Math.max(days.length, 1))} min/day`);
  if (weight) L.push(`Weight: ${weight.start} kg -> ${weight.end} kg (${weight.change > 0 ? '+' : ''}${weight.change} kg)`);
  L.push('');

  h('DAILY SUMMARY');
  L.push(`${pad('Date', 11)}${lpad('kcal', 6)}${lpad('Prot', 6)}${lpad('Carb', 6)}${lpad('Fat', 6)}${lpad('Fibre', 6)}${lpad('Sugar', 6)}${lpad('Water', 7)}${lpad('Ex min', 8)}${lpad('Wt kg', 8)}`);
  for (const d of days) {
    L.push(`${pad(d.date, 11)}${lpad(r0(d.calories) || '-', 6)}${lpad(d.calories ? r0(d.protein) : '-', 6)}${lpad(d.calories ? r0(d.carbohydrates) : '-', 6)}${lpad(d.calories ? r0(d.fat) : '-', 6)}${lpad(d.calories ? r1(d.fiber) : '-', 6)}${lpad(d.calories ? r0(d.sugar) : '-', 6)}${lpad(d.waterMl || '-', 7)}${lpad(d.exerciseMinutes || '-', 8)}${lpad(d.weighIn ? r1(d.weightKg) : '-', 8)}`);
  }
  L.push('');

  if (foodLogs?.length) {
    h('FOOD DIARY');
    const byDate = new Map();
    for (const f of foodLogs) { if (!byDate.has(f.date)) byDate.set(f.date, []); byDate.get(f.date).push(f); }
    for (const date of [...byDate.keys()].sort()) {
      L.push(date);
      for (const meal of MEAL_ORDER) {
        for (const f of byDate.get(date).filter((x) => x.mealType === meal)) {
          const n = f.nutritionTotal || {};
          L.push(`  ${pad(meal, 10)}${pad(f.foodName, 38)}${lpad(`${r1(f.consumedQuantity)}${f.servingUnit}`, 9)}${lpad(r0(n.calories), 6)}k ${lpad(r0(n.protein), 3)}P ${lpad(r1(n.fiber), 4)}F`);
        }
      }
    }
    L.push('');
  }
  L.push('Generated by FlexFit. Nutrition values are estimates based on the foods and quantities the user logged.');
  return L;
}

module.exports = { buildReportLines };
